Website = "https://github.com/shanepaton/shinecast"

[Details]
Icon = "Icon.png"
Name = "shinecast"
ID = "ca.shanepaton.shinecast"
Version = "1.0.0"
Build = 1

[LinuxAndBSD]
GenericName = "shinecast"
Categories = ["Multimedia"]
Comment = "A SSBM streaming tool."
Keywords = ["streaming", "media"]